
func binary() {
    a:int = 10;
    b:int = 20;

    c:int = a + b; @assert(c == 30);
    d:int = a - b; @assert(d == -10);
    e:int = a * b; @assert(e == 200);
    f:int = b / a; @assert(f == 2);
    f2:int = b % 3; @assert(f2 == 2);

    g:int = a << 1; @assert(g == 20);
    h:int = a >> 1; @assert(h == 5);

    // 10 = 1010
    i:int = a & 2; @assert(i == 2);
    j:int = a | 1; @assert(j == 11);
    k:int = a ^ 0b11; @assert(k == 9);

    // ~1010 = 11110101 = 245u = -11
    l:int = ~a; @assert(l == -11);

    m:int = -a; @assert(m == -10);

    n:int = a < 20; @assert(n);
    n2:int = a <= 10; @assert(n2);

    o:int = a > 5; @assert(o);
    o2:int = a >= 10; @assert(o2);

    p:int = a == (b-10); @assert(p);
    p2:int = a != 0; @assert(p2);

    q:int = a < 20 and b > a; @assert(q);
    q2:int = a < 20 or b < a; @assert(q2);

    q3:bool = false or true; @assert(q3);
    q4:bool = true and false; @assert(not q4);
    q5:bool = true and true; @assert(q5);

    a += 1; @assert(a==11);
    a -= 1; @assert(a==10);
    a *= 2; @assert(a==20);
    a /= 2; @assert(a==10);
    a %= 3; @assert(a==1);
    a <<= 1; @assert(a==2);
    a >>= 1; @assert(a==1);

    // b = 20 = 0b10100
    b &= 0b111; @assert(b==4);
    b |= 0b1000; @assert(b==12);

    // b = 12 = 0b1100
    b ^= 0b1111; @ assert(b==0b11);

    boo:bool = true;
    boo &= false; @assert(boo==false);
    boo |= true; @assert(boo==true);

    r:int = 7;
    r = 8; @assert(r==8);
}
