

func variables() {
    bool a1; @assert(not a1);
    bool a2 = true; @assert(a2);

    byte b1; @assert(b1==0);
    byte b2 = 1; @assert(b2==1);

    ubyte c1; @assert(c1==0);
    ubyte c2 = 2; @assert(c2==2);

    short d1; @assert(d1==0);
    short d2 = 3; @assert(d2==3);

    ushort e1; @assert(e1==0);
    ushort e2 = 4; @assert(e2==4);

    int f1; @assert(f1==0);
    int f2 = 5; @assert(f2==5);

    uint g1; @assert(g1==0);
    uint g2 = 6; @assert(g2==6);

    long h1; @assert(h1==0);
    long h2 = 7; @assert(h2==7);

    ulong i1; @assert(i1==0);
    ulong i2 = 8; @assert(i2==8);

    float j1; @assert(j1==0.0f);
    float j2 = 9.1; @assert(j2==9.1f);

    double k1; @assert(k1==0.0);
    double k2 = 10; @assert(k2==10.0);

    MyStruct l;
    // TODO - struct literals

    // TODO Function ptrs 
    (int a,float->void) fp;
    (void->void*) fp2;

    // TODO Union
}

struct MyStruct {
    int a;
}